### ISSUE TITLE
Plugin for Grafana v7.4.0

### ISSUE THREAD

**Issue by veeloup** [marcusolsson/grafana-json-datasource#143] opened 2021-07-15 11:32 UTC
Hello,
First of all: thanks for this amazing plugin it helped us a lot in building amazing Grafana dashboards.

We noticed, that after upgrading from Grafana v7.3.5 (11f305f88a) to Grafana v7.4.0 (c2203b9859) the plugin stopped working. With v7.4.0 we get the error "JSON API: Cannot connect to API" when trying to hit "test" under datasource settings. In the release notes of v7.4.0-beta I found the following:

Plugin compatibility
We have upgraded AngularJS from version 1.6.6 to 1.8.2. Due to this upgrade some old angular plugins might stop working and will require a small update. This is due to the deprecation and removal of pre-assigned bindings. So if your custom angular controllers expect component bindings in the controller constructor you need to move this code to an $onInit function. For more details on how to migrate AngularJS code open the migration guide and search for pre-assigning bindings.

source: https://github.com/grafana/grafana/releases/tag/v7.4.0-beta1

Is it related to this plugin?
Thanks for your review!

**Comment by marcusolsson** [comment] 2021-07-15 11:35
Thank you for the kind words! 🙏 

The JSON API plugin is written using the new React-based plugin platform and should be affected by the change you're referring to.

Could you try with a more recent version and see if it starts working again?

**Comment by veeloup** [comment] 2021-07-15 11:59
Just updated to v8.0.1 (8849243d27), unfortunately same issue.

**Comment by marcusolsson** [comment] 2021-07-15 12:02
Have you tried it with other URLs, e.g. https://grafana.com/api/plugins?

Are you using any authentication for you endpoint?

**Comment by veeloup** [comment] 2021-07-15 12:32
I am using Basic auth with credentials and "skip tls verify" enabled.
Just tried a different URL,which supports tls and does not need authentication and also getting "JSON API: Cannot connect to API"

**Comment by marcusolsson** [comment] 2021-07-15 12:36
Is there a public URL that I can try to reproduce this with?

**Comment by veeloup** [comment] 2021-07-19 08:01
As I am working on an air-gapped infrastructure, I can't access any public urls to reproduce. The only thing I was able to identify is, that it happens with these settings:
basicAuth: true
withCredentials: true
basicAuthUser: user
basicAuthPassword: password
Skip TLS Verify = true
Custom HTTP Headers: Accept: application/json

Having an url without Auth / Crendentials and Skip TLS setting works.

**Comment by veeloup** [comment] 2021-07-19 10:27
After some more testing I gained some more insights.
In my datasource I use `https://my.api.com` --> Testing the datasource returns **JSON API: Cannot connect to API**. This behavior came with v7.4.0.

However, my dashboard works fine with Grafana 8.0.5. JSON data are displayed.
On the panel properties under path I only use the suffix `/list/service_state=1`. This returns valid data from the api source.

Should we, from now on, provide a valid json url for the datasource? Like concatenating both to `https://my.api.com/list/service_state=1` ?

**Comment by marcusolsson** [comment] 2022-03-09 14:10
Sounds like this could be an issue with Grafana itself. The plugin doesn't actually craft the request itself, but leaves it to the Grafana data source proxy. Especially since it works with a more recent version of Grafana. I'll go ahead and close this issue. 

Regarding the question on using the path. The path set by the panel configuration appends the path instead of overriding it, so you can use both.

**Closed by marcusolsson** 2022-03-09 14:10 UTC
Labels: priority/awaiting-more-evidence, kind/support
