### ISSUE TITLE
Passing a '/' into Path

### ISSUE THREAD

**Issue by MathieuEtchepare** [marcusolsson/grafana-json-datasource#215] opened 2021-12-06 10:46 UTC
Hello,

I'm using your plugin to query my rabbitMQ cluster's API and as a parameter I must pass a '/'
Using urlencode, / = %2F
The query gives a path like this: /queues/%2F/name_of_queue

But when going through the plugin, it seems to be decoded as /queues///name_of_queue which doesn't work.

Is there a way to work this around?

Thank you

**Comment by jonnor** [comment] 2021-12-09 09:23
This seems related to / possibly a duplicate of #59

**Comment by marcusolsson** [comment] 2021-12-11 07:35
Thanks @jonnor for spotting 🙏 I'm closing this as a duplicate. Please continue the discussion in #59.

**Closed by marcusolsson** 2021-12-11 07:35 UTC
Labels: triage/duplicate
