### ISSUE TITLE
Field cannot be select based on variable using JSONpath

### ISSUE THREAD

**Issue by valdemarpavesi** [marcusolsson/grafana-json-datasource#168] opened 2021-09-09 00:38 UTC
on previous version this query was working fine:  

`$.[?(@.parent_cluster_name == "$parent_cluster_name")].cluster_name`

on new Release v1.3.0 it will fail with error:

jsonPath: Cannot read properties of null (reading 'parent_cluster_name'): _$_v.parent_cluster_name == "xxxx.xxxx"

**Comment by marcusolsson** [comment] 2021-09-09 17:52
Thanks for reporting! 

Would you be able to [create a GitHub Gist](https://gist.github.com/) with a sample payload that I can reproduce this with?

**Comment by valdemarpavesi** [comment] 2021-09-09 18:57
thanks, Marcus, let me see If I can reproduce with grafana-api.

and using  grafana/grafana:8.1.3-ubuntu

**Comment by valdemarpavesi** [comment] 2021-09-09 19:41
yes. problem is interesting.
i did created 1600 datasource on grafana
and there is no problem
![image](https://user-images.githubusercontent.com/10376101/132751692-f47a1c3c-c2b2-4006-a1c5-cf02bb3256d2.png)

variable name from /api/datasources
![image](https://user-images.githubusercontent.com/10376101/132751789-27bc03f0-670e-4eb0-95be-43ad85dc80d9.png)

and get typeLogoUrl based on selected name:
$.[?(@.name == "$name")].typeLogoUrl

![image](https://user-images.githubusercontent.com/10376101/132751929-cc0d6326-8b2f-46b4-b865-2b2381414171.png)

all working fine.

let see....

**Comment by valdemarpavesi** [comment] 2021-09-09 20:10
it is a simple structure:
```

[
    {
        "f1":1,
        "f2":"2:2"
        
    }
]
```

25 fields and 1600 entries.

**Comment by marcusolsson** [comment] 2022-03-09 14:27
Looks like it's working for you, so I'll close the issue for now. Let me know if the problem persists.

**Closed by marcusolsson** 2022-03-09 14:27 UTC
Labels: priority/awaiting-more-evidence, kind/support
