### ISSUE TITLE
Cannot read property 'length' of null

### ISSUE THREAD

**Issue by naman7kr** [marcusolsson/grafana-json-datasource#21] opened 2020-12-02 03:14 UTC
I am getting this error when I tried to access "createdBy" ($.[*].createdBy) from the jsonFile (https://github.com/marcusolsson/grafana-json-datasource/files/5626718/error_json.txt). When I changed the value of first "createdBy" to string and second "createdBy" to null, then the error vanishes and I get the required table. So if any value in the first row of the table is null, then the table crashes and I get this error. 

[error_json.txt](https://github.com/marcusolsson/grafana-json-datasource/files/5626718/error_json.txt)

**Comment by jinxiao** [comment] 2020-12-02 07:23
I think I have the same problem.
I change a value field to null , then it turned to error.
For this scenario, we changed null to "null", ie, make it a string , then it works.

**Comment by marcusolsson** [comment] 2020-12-02 16:57
Thanks for reporting this! 🙏 I can confirm that I'm able to reproduce this. Will debug and get back to you!

**Comment by marcusolsson** [comment] 2020-12-03 15:47
The schema detection fails because the `null` values. I've submitted a fix for this in https://github.com/marcusolsson/grafana-json-datasource/commit/4f8cd797d3bca9c34ab3470de31a39ac17243f3d. 

I'd like to add a few more fixes because I create a new release. Hope that's ok with you! 🙏

**Closed by marcusolsson** 2020-12-03 15:47 UTC
Labels: bug

**Comment by naman7kr** [comment] 2020-12-04 16:58
Version [0.7.0](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/installation) Works like a charm. Thanks!!
