### ISSUE TITLE
Is there a way to serve for Pie chart

### ISSUE THREAD

**Issue by smarkm** [marcusolsson/grafana-json-datasource#45] opened 2021-02-01 00:07 UTC
I am trying to build a pie chart use this datasource, but I did not find the right way

**Comment by marcusolsson** [comment] 2021-02-01 10:05
I just tried it as well. The problem is that the pie chart expects a multiple series with one row, rather than one series with multiple rows, as the JSON data source currently returns. 

Normally you could instead create several data source queries and filter the results in each, but since the pie chart doesn't support the new field options yet, you can't create aliases for properties with the same name.

To dynamically create series from a single data source query, we'd have to implement some kind of Group by functionality, where you'd select the property you'd want to group on, using a JSON Path. 

There's already an issue for this here: https://github.com/marcusolsson/grafana-json-datasource/issues/36

I'll close this issue in favor of the one I mentioned.

**Closed by marcusolsson** 2021-02-01 10:05 UTC
