### ISSUE TITLE
UI glitch on Panel configuration.

### ISSUE THREAD

**Issue by gdassori** [marcusolsson/grafana-json-datasource#103] opened 2021-04-26 09:09 UTC
While editing the panel configuration, using the JSON API data source, my variables overflow into the configuration panel, going above the settings.

This happens when a dashboard has a lot of variables.

I worked around this issue with a custom CSS rule. 
```
.Pane2 {z-index: 1}
```

**Comment by marcusolsson** [comment] 2021-04-26 09:20
Thank you for reporting!

**Comment by marcusolsson** [comment] 2021-12-17 15:52
I can't seem to reproduce this. Closing this for now since it's been a while, but let me know if the issue remains and how I can reproduce it.

**Closed by marcusolsson** 2021-12-17 15:52 UTC
Labels: kind/bug, priority/awaiting-more-evidence, triage/not-reproducible
